- name: Installing nginx
  ansible.builtin.package:
    name: nginx
    state: present

- name: start nginx server
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
    
- name: import from common role
  ansible.builtin.import_role:
    name: common
    tasks_from: prereq

# - name: Remve html content in nginx
#   ansible.builtin.file:
#     path: /usr/share/nginx/html/
#     state: absent

# - name: Create html dir 
#   ansible.builtin.file:
#     path: /usr/share/nginx/html/
#     state: directory

# - name: Download application code 
#   ansible.builtin.get_url:
#     url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
#     dest: /tmp/frontend.zip

# - name: Extract the code into html directory
#   ansible.builtin.unarchive:
#     src: /tmp/frontend.zip
#     dest: /usr/share/nginx/html/
#     remote_src: yes

- name: copy expense conf
  ansible.builtin.templete:
    src: expense.conf.j2
    dest: /etc/nginx/default.d/expense.conf
  notify:
  - restart nginx
